module.exports = {  
    welcomeMsg: "Welcome to Airbnb Empire, future landlords! I am Infi, your AI advisor. You can click on my office for hints if you need help during the game.",
    introMsg1: "I am providing you with an investment of £200K to invest in properties with the aim to convert them into AirBnBs. I want you to achieve a net rental yield of 8% by the end of the year.",
    introMsg2: "In order to meet this goal, you will need to invest wisely to ensure good rental income, positive net cash flow and an increase in property value over one year. You can track your performance by clicking on the button above.",
    introMsg3: "Are you ready to make money?",
    introMsg4: "Here are some properties that are available for sale. You can purchase these properties with cash or finance them with a mortgage. Click on each property and the surrounding area for more information.",
    successMsg: "Congratulations! You achieved a rental yield of above 8%! Before accessing your personalised feedback report, let's watch this debriefing video by Doraemon.",
    failMsg: "You did not meet the goal of an 8% rental yield. Before accessing your personalised feedback report, let's watch this debriefing video by ?. Hopefully, you can learn from your mistakes and do better next time.",
    readyMsg: "Are you ready to make money?",
    testVideoSource: 'https://gdurl.com/PjVU',
    handsUpImg : require('../assets/Infi/Hands up in the air.png'),
    pointingImg: require('../assets/Infi/Pointing.png'),
    cityImg: require('../assets/city.jpg'),
    cityBannerImg: require('../assets/city-with-banner.png'),
    cityPropertiesImg: require('../assets/city-with-properties.png'),
    winterIcon: require('../assets/Seasons/SnowflakeIcon.png'),
    springIcon: require('../assets/Seasons/SpringFlower.png'),
    summerIcon: require('../assets/Seasons/SunIcon.png'),
    autumnIcon: require('../assets/Seasons/AutumnLeaf.png'),
    graphIcon: require('../assets/graph-icon.png'),
    pointerImg: require('../assets/pointer.png'),
    propertyInfoPtr: require('../assets/pointers/propertyInfoPointer.png'),
    infiHQptr: require('../assets/pointers/infiHQpointer.png'),
    location1Ptr: require('../assets/pointers/location1ptr.png'),
    location2Ptr: require('../assets/pointers/location2ptr.png'),
    location3Ptr: require('../assets/pointers/location3ptr.png'),
} 